[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  GAS_URL = "https://script.google.com/macros/s/AKfycbz2N1STuIJQFWg9f47ZeiXedIWY0unzcX4HfkRaYiFDziJ_htz6Tp0jHsPoUy-F-Qyv"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
